// Compiler definition

{.$DEFINE ConsoleApp} // if FPC version < 2.7.1 uncomment for console application
{.$DEFINE library}   // uncomment for building uos library (native and java)
{.$DEFINE java}   // uncomment for building uos java library

{$DEFINE portaudio} // uncomment to enable portaudio compiling
{$DEFINE sndfile} // uncomment to enable sndfile compiling
{$DEFINE mpg123} // uncomment to enable mpg123 compiling
{$DEFINE soundtouch} // uncomment to enable soundtouch compiling
{$DEFINE bs2b} // uncomment to enable bs2b compiling
{$DEFINE webstream} // uncomment to enable Internet Audio Stream      
